### ISSUE TITLE
subject_prefix is never used?

### ISSUE THREAD

**Issue by rogamoore** [zenstruck/schedule-bundle#21]
Thank you for this really nice bundle!

I was just testing the email notification on failure and I noticed that the `subject_prefix` option as documented in the configuration reference https://github.com/zenstruck/schedule-bundle#full-configuration-reference didn't work as expected.

I didn't have time to debug it in detail, but my initial guess is that while the EmailHandler accepts the subject_prefix in the constructor (https://github.com/zenstruck/schedule-bundle/blob/master/src/Schedule/Extension/Handler/EmailHandler.php#L27) this argument is missing in the service definition here https://github.com/zenstruck/schedule-bundle/blob/master/src/Resources/config/mailer.xml.

I will have a better look later and submit a PR if applicable.

**Comment by kbond** [comment]
Hmm, I confirmed in one of my apps that it is indeed working for me. The argument is missing in the service definition but added in the extension: 

https://github.com/zenstruck/schedule-bundle/blob/f2602896f96d4bbf0942923f9309922976884e04/src/DependencyInjection/ZenstruckScheduleExtension.php#L109-L121

Can you share your (obfuscated) config and where you are configuring the email extension for your task/schedule?

**Comment by rogamoore** [comment]
Hm, if it works for you, then I should probably do some more debugging.

My config looks like this:

```yaml
zenstruck_schedule:
    timezone: UTC
    without_overlapping_lock_factory: lock.cron.factory
    single_server_lock_factory: lock.cron.factory
    schedule_extensions:
        on_single_server:
            enabled: true
            ttl: 3600
        email_on_failure:
            enabled: true
    mailer:
        service: mailer
        default_to: mail_to@example.org
        default_from: mail_from@example.org
        subject_prefix: "[my custom prefix]"
    tasks:
        - task: test
          frequency: "0 10 * * 7" # every sunday at 10am
          description: "test"
          without_overlapping: ~

```

The subject I get when making the "test" task fail on purpose is:
```
[Schedule Failure] 1 task failed
```
