### ISSUE TITLE
Commands not running automaticallty

### ISSUE THREAD

**Issue by Zgon7** [zenstruck/schedule-bundle#43]
I have a command scheduled to run every minute,
when I type `php bin/console schedule:list --detail`
I can see next run in 1 mn. But it doesn't run autimarically until I type
`php bin/console schedule:run`
Any ideas how to make it run automatically ? Thanks

**Comment by kbond** [comment]
Hello, you need to [setup your production server](https://github.com/zenstruck/schedule-bundle/blob/master/doc/run-schedule.md) to run the `schedule:run` every minute (cron job).

**Comment by Zgon7** [comment]
I'm using Symfony 4.4 and still in dev mode (Windows OP).
here's the eror I got when I setup the symfony.cloud.yaml

In Parser.php line 720:
                                                                           
  Reference " * * * *" does not exist at line 1 (near "spec: * * * * *").

**Comment by kbond** [comment]
Oh, you're using Symfony Cloud? I've never actually tested or seen it being used with this bundle in the wild so this will be a learning experience.

I'm seeing my docs linked above are outdated/incorrect. What about:

```yaml
crons:
    zenstruck_schedule:
        # every minute
        spec: * * * * *
        cmd: croncape bin/console schedule:run
```
